import { NowPlayingAwareScrollView } from '@/components/playback/NowPlayingAwareScroll';
import { useEffect, useState, useSyncExternalStore } from 'react';
import { Alert, Platform, Pressable, StyleSheet, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import AppHeader from '@/components/chc/ui/AppHeader'; import ToggleRow from '@/components/chc/ui/ToggleRow';
import { COLORS, RADII, SPACING, TYPOGRAPHY } from '@/constants/theme'; import { useReadingPreferences } from '@/context/ReadingPreferencesContext';
import { downloadManager } from '@/services/downloadManager'; import { getDownloadPreferences, setDownloadPreferences, type DownloadPreferences } from '@/services/downloadPreferences';
import type { OfflineDownloadProgress, OfflineStorageSummary } from '@/types/offlineDownloads'; import { goBack } from '@/utils/navigation';
const EMPTY: OfflineStorageSummary = { packageCount: 0, completeCount: 0, failedCount: 0, totalBytes: 0, musicBytes: 0, learningBytes: 0 };
function bytes(value: number): string { if (value < 1024) return `${value} B`; if (value < 1024 ** 2) return `${(value / 1024).toFixed(1)} KB`; if (value < 1024 ** 3) return `${(value / 1024 ** 2).toFixed(1)} MB`; return `${(value / 1024 ** 3).toFixed(2)} GB`; }
export default function DownloadsScreen() {
  const router = useRouter(); const { preferences: reading } = useReadingPreferences(); const isArabic = reading.appLanguage === 'ar'; const revision = useSyncExternalStore(downloadManager.subscribe, downloadManager.getRevision, downloadManager.getRevision);
  const [summary, setSummary] = useState<OfflineStorageSummary>(EMPTY); const [items, setItems] = useState<OfflineDownloadProgress[]>([]); const [prefs, setPrefs] = useState<DownloadPreferences>({ wifiOnly: false, allowCellular: true, allowVideoOnCellular: false }); const [busy, setBusy] = useState(false);
  useEffect(() => { let active = true; void Promise.all([downloadManager.getStorageSummary(), downloadManager.listDownloads(), getDownloadPreferences()]).then(([nextSummary, nextItems, nextPrefs]) => { if (!active) return; setSummary(nextSummary); setItems(nextItems); setPrefs(nextPrefs); }); return () => { active = false; }; }, [revision]);
  const patch = async (value: Partial<DownloadPreferences>) => { setPrefs(await setDownloadPreferences(value)); };
  const maintenance = async (kind: 'validate' | 'cleanup') => { setBusy(true); try { if (kind === 'validate') { const result = await downloadManager.validateIntegrity(); Alert.alert('Download check', result.invalid ? `${result.invalid} of ${result.checked} files need to be downloaded again.` : `${result.checked} downloaded files passed validation.`); } else { const count = await downloadManager.cleanupIncomplete(); Alert.alert('Cleanup complete', `${count} incomplete file${count === 1 ? '' : 's'} cleaned up.`); } } finally { setBusy(false); } };
  const removeAll = () => Alert.alert('Remove all downloads?', 'All downloaded Music and Learn & Study media will be removed from this device.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Remove All', style: 'destructive', onPress: () => { void downloadManager.removeAll(); } }]);
  return <SafeAreaView edges={['left', 'right', 'bottom']} style={styles.safe}><AppHeader title={{ english: 'Downloads & Storage', arabic: 'التنزيلات والتخزين' }} canGoBack onBack={() => goBack(router, '/settings')} visibleLanguages={{ english: !isArabic, arabic: isArabic }} /><NowPlayingAwareScrollView contentContainerStyle={styles.content}>
    <View style={styles.card}><Text style={styles.heading}>Storage</Text><Text style={styles.total}>{bytes(summary.totalBytes)}</Text><Text style={styles.muted}>Music {bytes(summary.musicBytes)} • Learn & Study {bytes(summary.learningBytes)}</Text><Text style={styles.muted}>{summary.completeCount} downloaded • {summary.failedCount} need attention</Text></View>
    {Platform.OS === 'web' ? <View style={styles.card}><Text style={styles.muted}>Offline media downloads are managed in the CHC iOS and Android apps.</Text></View> : <><View style={styles.card}><Text style={styles.heading}>Download preferences</Text><ToggleRow label="Wi-Fi only downloads" active={prefs.wifiOnly} onPress={() => void patch({ wifiOnly: !prefs.wifiOnly, allowCellular: prefs.wifiOnly ? prefs.allowCellular : false })} /><ToggleRow label="Allow cellular downloads" active={prefs.allowCellular && !prefs.wifiOnly} onPress={() => void patch({ allowCellular: !prefs.allowCellular, wifiOnly: prefs.allowCellular ? true : false })} /><ToggleRow label="Allow video over cellular" active={prefs.allowVideoOnCellular} onPress={() => void patch({ allowVideoOnCellular: !prefs.allowVideoOnCellular })} /></View>
    <View style={styles.card}><Text style={styles.heading}>Maintenance</Text><Pressable disabled={busy} style={styles.action} onPress={() => void maintenance('validate')}><Text style={styles.actionText}>Verify downloaded files</Text></Pressable><Pressable disabled={busy} style={styles.action} onPress={() => void maintenance('cleanup')}><Text style={styles.actionText}>Clean incomplete downloads</Text></Pressable><Pressable style={[styles.action, styles.danger]} onPress={removeAll}><Text style={styles.dangerText}>Remove All Downloads</Text></Pressable></View>
    <View style={styles.card}><Text style={styles.heading}>Downloaded library</Text>{items.length === 0 ? <Text style={styles.muted}>No downloads yet.</Text> : items.map((item) => <View key={item.packageKey} style={styles.item}><View style={{ flex: 1 }}><Text style={styles.itemTitle}>{item.title}</Text><Text style={styles.muted}>{item.domain === 'music' ? 'Music' : 'Learn & Study'} • {item.status}</Text></View><Text style={styles.size}>{bytes(item.bytesWritten)}</Text><Pressable onPress={() => void downloadManager.remove(item.packageKey)}><Text style={styles.remove}>Remove</Text></Pressable></View>)}</View></>}</NowPlayingAwareScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: COLORS.black }, content: { padding: SPACING.md, gap: SPACING.md, paddingBottom: SPACING.xl }, card: { backgroundColor: COLORS.navy, borderColor: COLORS.border, borderWidth: 1, borderRadius: RADII.lg, padding: SPACING.md, gap: SPACING.sm }, heading: { color: COLORS.white, fontFamily: TYPOGRAPHY.body, fontWeight: '800', fontSize: 16 }, total: { color: COLORS.goldBright, fontSize: 28, fontWeight: '800' }, muted: { color: COLORS.muted, fontSize: 13 }, action: { minHeight: 44, borderColor: COLORS.border, borderWidth: 1, borderRadius: RADII.md, alignItems: 'center', justifyContent: 'center' }, actionText: { color: COLORS.white, fontWeight: '700' }, danger: { borderColor: '#8f3f45' }, dangerText: { color: '#ff8e96', fontWeight: '800' }, item: { flexDirection: 'row', alignItems: 'center', gap: SPACING.sm, borderTopColor: COLORS.border, borderTopWidth: 1, paddingTop: SPACING.sm }, itemTitle: { color: COLORS.white, fontWeight: '700' }, size: { color: COLORS.muted, fontSize: 12 }, remove: { color: COLORS.goldBright, fontWeight: '700', fontSize: 12 } });
