-- Native offline Books package registry, consistent snapshot staging, and
-- direct-database change detection. Package objects are generated by the
-- Cloudflare content-packages Worker and never reconstructed by app clients.

create schema if not exists offline_content;
revoke all on schema offline_content from public, anon, authenticated;
grant usage on schema offline_content to service_role;

create table if not exists offline_content.resources (
  resource_key text primary key,
  schema_name text not null unique,
  include_tables text[],
  revision bigint not null default 1,
  dirty boolean not null default true,
  updated_at timestamptz not null default now(),
  constraint resource_key_format check (resource_key ~ '^[a-z][a-z0-9_]*$')
);

create table if not exists offline_content.resource_dependencies (
  resource_key text not null references offline_content.resources(resource_key) on delete cascade,
  dependency_key text not null references offline_content.resources(resource_key) on delete restrict,
  primary key (resource_key, dependency_key),
  constraint no_self_dependency check (resource_key <> dependency_key)
);

create table if not exists offline_content.books (
  book_key text primary key,
  title_english text not null,
  title_arabic text not null,
  root_resources text[] not null,
  enabled boolean not null default true
);

create table if not exists offline_content.snapshots (
  snapshot_id uuid primary key default gen_random_uuid(),
  status text not null default 'staging' check (status in ('staging', 'ready', 'published', 'failed')),
  created_at timestamptz not null default now(),
  published_at timestamptz,
  error text
);

create table if not exists offline_content.snapshot_resources (
  snapshot_id uuid not null references offline_content.snapshots(snapshot_id) on delete cascade,
  resource_key text not null references offline_content.resources(resource_key) on delete restrict,
  version text not null,
  primary key (snapshot_id, resource_key)
);

create table if not exists offline_content.snapshot_rows (
  row_id bigint generated always as identity primary key,
  snapshot_id uuid not null references offline_content.snapshots(snapshot_id) on delete cascade,
  resource_key text not null,
  row_kind text not null check (row_kind in ('table', 'rpc')),
  schema_name text not null,
  object_name text not null,
  args_json jsonb,
  payload jsonb not null
);
create index if not exists offline_snapshot_rows_export_idx
  on offline_content.snapshot_rows(snapshot_id, resource_key, row_id);

create table if not exists offline_content.publication_requests (
  request_id bigint generated always as identity primary key,
  status text not null default 'queued' check (status in ('queued', 'processing', 'complete', 'failed')),
  snapshot_id uuid references offline_content.snapshots(snapshot_id) on delete set null,
  requested_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz,
  error text
);
create unique index if not exists one_pending_offline_publication
  on offline_content.publication_requests ((true)) where status in ('queued', 'processing');

insert into offline_content.resources(resource_key, schema_name, include_tables) values
  ('public', 'public', array['hymn_titles','hymn_texts','saint_order']),
  ('calendar', 'calendar', array['coptic_date_conversions','season_ranges','reading_rules','condition_flags']),
  ('bible', 'bible', array['books','verses','verse_parts']),
  ('agpeya', 'agpeya', null),
  ('canons', 'canons', null),
  ('doxologies', 'doxologies', null),
  ('gospel_rite', 'gospel_rite', null),
  ('gospel_responses', 'gospel_responses', null),
  ('hymn_of_the_intercessions', 'hymn_of_the_intercessions', null),
  ('litanies', 'litanies', null),
  ('praxis_response', 'praxis_response', null),
  ('readings', 'readings', null),
  ('synaxarium', 'synaxarium', null),
  ('verses_of_the_cymbals', 'verses_of_the_cymbals', null),
  ('psalmody', 'psalmody', null),
  ('veneration', 'veneration', null),
  ('liturgy', 'liturgy', null)
on conflict (resource_key) do update set
  schema_name = excluded.schema_name,
  include_tables = excluded.include_tables;

insert into offline_content.resource_dependencies(resource_key, dependency_key) values
  ('bible','public'), ('agpeya','public'), ('agpeya','bible'), ('canons','public'), ('doxologies','public'),
  ('gospel_rite','public'), ('gospel_rite','bible'), ('gospel_rite','calendar'),
  ('gospel_responses','public'), ('hymn_of_the_intercessions','public'), ('litanies','public'),
  ('praxis_response','public'), ('readings','public'), ('readings','bible'), ('readings','calendar'),
  ('synaxarium','calendar'), ('verses_of_the_cymbals','public'),
  ('psalmody','public'), ('psalmody','agpeya'), ('psalmody','doxologies'), ('psalmody','canons'), ('psalmody','bible'), ('psalmody','calendar'),
  ('veneration','public'), ('veneration','doxologies'), ('veneration','verses_of_the_cymbals'),
  ('veneration','hymn_of_the_intercessions'), ('veneration','praxis_response'), ('veneration','psalmody'), ('veneration','calendar'),
  ('liturgy','public'), ('liturgy','verses_of_the_cymbals'), ('liturgy','doxologies'), ('liturgy','bible'),
  ('liturgy','gospel_rite'), ('liturgy','gospel_responses'), ('liturgy','agpeya'),
  ('liturgy','hymn_of_the_intercessions'), ('liturgy','readings'), ('liturgy','praxis_response'),
  ('liturgy','litanies'), ('liturgy','synaxarium'), ('liturgy','psalmody'), ('liturgy','veneration'), ('liturgy','calendar')
on conflict do nothing;

insert into offline_content.books(book_key, title_english, title_arabic, root_resources) values
  ('psalmody','Psalmody','الإبصلمودية',array['psalmody']),
  ('liturgy','Liturgy','القداس',array['liturgy']),
  ('veneration','Veneration','تمجيد',array['veneration']),
  ('agpeya','Agpeya','الأجبية',array['agpeya']),
  ('bible','Bible','الكتاب المقدس',array['bible'])
on conflict (book_key) do update set title_english=excluded.title_english,
  title_arabic=excluded.title_arabic, root_resources=excluded.root_resources;

create or replace function offline_content.mark_resource_dirty()
returns trigger language plpgsql security definer set search_path = '' as $$
declare v_resource text;
begin
  select resource_key into v_resource from offline_content.resources where schema_name = tg_table_schema;
  if v_resource is null then return null; end if;
  update offline_content.resources set revision = revision + 1, dirty = true, updated_at = now()
    where resource_key = v_resource;
  insert into offline_content.publication_requests(status) values ('queued')
    on conflict do nothing;
  return null;
end $$;

create or replace function offline_content.refresh_change_triggers()
returns void language plpgsql security definer set search_path = '' as $$
declare rec record; trigger_name text;
begin
  for rec in
    select r.resource_key, r.schema_name, t.tablename
      from offline_content.resources r
      join pg_catalog.pg_tables t on t.schemaname = r.schema_name
     where (r.include_tables is null or t.tablename = any(r.include_tables))
       and t.tablename !~* '(backup|archive|history|working|staging|admin|draft|audit)'
  loop
    trigger_name := 'chc_offline_dirty_' || substr(md5(rec.schema_name || '.' || rec.tablename), 1, 16);
    if not exists (
      select 1
        from pg_catalog.pg_trigger tg
        join pg_catalog.pg_class c on c.oid=tg.tgrelid
        join pg_catalog.pg_namespace n on n.oid=c.relnamespace
       where not tg.tgisinternal and tg.tgname=trigger_name
         and n.nspname=rec.schema_name and c.relname=rec.tablename
    ) then
      execute format(
        'create trigger %I after insert or update or delete or truncate on %I.%I for each statement execute function offline_content.mark_resource_dirty()',
        trigger_name, rec.schema_name, rec.tablename
      );
      -- A newly discovered table may already contain data written before its
      -- trigger existed, so its resource must be republished immediately.
      update offline_content.resources
         set revision=revision+1, dirty=true, updated_at=now()
       where resource_key=rec.resource_key;
    end if;
  end loop;
end $$;

select offline_content.refresh_change_triggers();
insert into offline_content.publication_requests(status) values ('queued') on conflict do nothing;

create or replace function public.begin_offline_package_snapshot()
returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  v_snapshot uuid := gen_random_uuid();
  v_request bigint;
  r record;
  t record;
  d record;
  v_sql text;
  v_order_clause text;
begin
  if auth.role() <> 'service_role' then raise exception 'service_role required'; end if;
  perform pg_advisory_xact_lock(hashtext('chc-offline-package-publication'));
  update offline_content.publication_requests
     set status='failed', completed_at=now(), error='Publisher did not finish within one hour.'
   where status='processing' and started_at < now() - interval '1 hour';
  perform offline_content.refresh_change_triggers();

  select request_id into v_request from offline_content.publication_requests
   where status = 'queued' order by requested_at for update skip locked limit 1;
  if v_request is null and not exists(select 1 from offline_content.resources where dirty) then
    return jsonb_build_object('snapshotId', null, 'resources', '[]'::jsonb);
  end if;
  if v_request is not null then
    update offline_content.publication_requests set status='processing', started_at=now(), snapshot_id=v_snapshot where request_id=v_request;
  end if;
  insert into offline_content.snapshots(snapshot_id, status) values (v_snapshot, 'staging');

  for r in select * from offline_content.resources where dirty order by resource_key loop
    insert into offline_content.snapshot_resources(snapshot_id, resource_key, version)
      values (v_snapshot, r.resource_key, r.revision::text);
    for t in
      select tablename from pg_catalog.pg_tables
       where schemaname=r.schema_name
         and (r.include_tables is null or tablename=any(r.include_tables))
         and tablename !~* '(backup|archive|history|working|staging|admin|draft|audit)'
       order by tablename
    loop
      v_order_clause := case
        when r.resource_key = 'bible' and t.tablename = 'books'
          then 'source_number nulls last, book_key'
        when r.resource_key = 'bible' and t.tablename = 'verses'
          then 'book_key, chapter_number, verse_number'
        when r.resource_key = 'bible' and t.tablename = 'verse_parts'
          then 'book_key, chapter_number, verse_number, part_label'
        else 'to_jsonb(source_row)::text'
      end;
      v_sql := format(
        'insert into offline_content.snapshot_rows(snapshot_id,resource_key,row_kind,schema_name,object_name,payload)
         select $1,$2,''table'',$3,$4,to_jsonb(source_row) from %I.%I source_row order by %s',
        r.schema_name, t.tablename, v_order_clause
      );
      execute v_sql using v_snapshot, r.resource_key, r.schema_name, t.tablename;
    end loop;

    -- RPCs whose server logic cannot be reduced to a table lookup are
    -- materialized for every packaged calendar date in the same transaction.
    if r.resource_key = 'calendar' then
      for d in select gregorian_date from calendar.coptic_date_conversions order by gregorian_date loop
        insert into offline_content.snapshot_rows(snapshot_id,resource_key,row_kind,schema_name,object_name,args_json,payload)
        values
          (v_snapshot,'calendar','rpc','calendar','get_context_flags',jsonb_build_object('p_date',d.gregorian_date,'p_extra_context','{}'::jsonb),to_jsonb(calendar.get_context_flags(d.gregorian_date,'{}'::jsonb))),
          (v_snapshot,'calendar','rpc','calendar','get_active_flags_for_date',jsonb_build_object('p_gregorian_date',d.gregorian_date),(select coalesce(jsonb_agg(to_jsonb(x)),'[]'::jsonb) from calendar.get_active_flags_for_date(d.gregorian_date) x)),
          (v_snapshot,'calendar','rpc','public','get_readings_for_date',jsonb_build_object('p_date',d.gregorian_date),(select coalesce(jsonb_agg(to_jsonb(x)),'[]'::jsonb) from public.get_readings_for_date(d.gregorian_date) x));
      end loop;
    elsif r.resource_key = 'synaxarium' then
      for d in select gregorian_date from calendar.coptic_date_conversions order by gregorian_date loop
        insert into offline_content.snapshot_rows(snapshot_id,resource_key,row_kind,schema_name,object_name,args_json,payload)
        values (v_snapshot,'synaxarium','rpc','synaxarium','get_day_json',jsonb_build_object('p_date',d.gregorian_date),to_jsonb(synaxarium.get_day_json(d.gregorian_date)));
      end loop;
    end if;
  end loop;
  update offline_content.snapshots set status='ready' where snapshot_id=v_snapshot;
  return jsonb_build_object(
    'snapshotId', v_snapshot,
    'resources', coalesce((select jsonb_agg(jsonb_build_object('id',resource_key,'version',version) order by resource_key)
      from offline_content.snapshot_resources where snapshot_id=v_snapshot),'[]'::jsonb)
  );
exception when others then
  if v_request is not null then update offline_content.publication_requests set status='failed', completed_at=now(), error=sqlerrm where request_id=v_request; end if;
  raise;
end $$;

create or replace function public.get_offline_package_registry(p_snapshot_id uuid)
returns jsonb language plpgsql security definer set search_path = '' as $$
begin
  if auth.role() <> 'service_role' then raise exception 'service_role required'; end if;
  return jsonb_build_object(
    'books', coalesce((select jsonb_agg(jsonb_build_object('key',book_key,'title',title_english,'titleArabic',title_arabic,'roots',root_resources) order by book_key) from offline_content.books where enabled),'[]'::jsonb),
    'dependencies', coalesce((select jsonb_agg(jsonb_build_object('resource',resource_key,'dependency',dependency_key) order by resource_key,dependency_key) from offline_content.resource_dependencies),'[]'::jsonb),
    'resources', coalesce((select jsonb_agg(jsonb_build_object('id',r.resource_key,'version',coalesce(sr.version,r.revision::text)) order by r.resource_key)
       from offline_content.resources r left join offline_content.snapshot_resources sr on sr.snapshot_id=p_snapshot_id and sr.resource_key=r.resource_key),'[]'::jsonb)
  );
end $$;

create or replace function public.get_offline_snapshot_rows(
  p_snapshot_id uuid,
  p_resource_key text,
  p_after_row_id bigint default 0,
  p_limit integer default 1000
)
returns table(row_id bigint,row_kind text,schema_name text,object_name text,args_json jsonb,payload jsonb)
language sql security definer set search_path = '' as $$
  select r.row_id,r.row_kind,r.schema_name,r.object_name,r.args_json,r.payload
    from offline_content.snapshot_rows r
   where r.snapshot_id=p_snapshot_id and r.resource_key=p_resource_key and r.row_id>p_after_row_id
   order by r.row_id
   limit least(greatest(p_limit,1),2000)
$$;

create or replace function public.finish_offline_package_snapshot(p_snapshot_id uuid, p_success boolean, p_error text default null)
returns void language plpgsql security definer set search_path = '' as $$
begin
  if auth.role() <> 'service_role' then raise exception 'service_role required'; end if;
  if p_success then
    update offline_content.resources r set dirty=false
      where exists(select 1 from offline_content.snapshot_resources sr where sr.snapshot_id=p_snapshot_id and sr.resource_key=r.resource_key and sr.version=r.revision::text);
    update offline_content.snapshots set status='published', published_at=now(), error=null where snapshot_id=p_snapshot_id;
    update offline_content.publication_requests set status='complete', completed_at=now(), error=null where snapshot_id=p_snapshot_id;
  else
    update offline_content.snapshots set status='failed', error=p_error where snapshot_id=p_snapshot_id;
    update offline_content.publication_requests set status='failed', completed_at=now(), error=p_error where snapshot_id=p_snapshot_id;
  end if;
end $$;

revoke all on function public.begin_offline_package_snapshot() from public, anon, authenticated;
revoke all on function public.get_offline_package_registry(uuid) from public, anon, authenticated;
revoke all on function public.get_offline_snapshot_rows(uuid,text,bigint,integer) from public, anon, authenticated;
revoke all on function public.finish_offline_package_snapshot(uuid,boolean,text) from public, anon, authenticated;
grant execute on function public.begin_offline_package_snapshot() to service_role;
grant execute on function public.get_offline_package_registry(uuid) to service_role;
grant execute on function public.get_offline_snapshot_rows(uuid,text,bigint,integer) to service_role;
grant execute on function public.finish_offline_package_snapshot(uuid,boolean,text) to service_role;
grant select on offline_content.snapshot_rows to service_role;
